server.port=8081
spring.application.name=rentacarnow

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5430/rentacarnow}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:rentacarnow}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:rentacarnow}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

app.upload.dir=${APP_UPLOAD_DIR:D:/Codigo/proy_final_dh/uploads/cars}
