server.port=8081
spring.application.name=rentacarnow

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5430/rentacarnow}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:rentacarnow}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:rentacarnow}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

app.upload.dir=${APP_UPLOAD_DIR:D:/Codigo/proy_final_dh/uploads/cars}

app.jwt.secret=${JWT_SECRET:c3VwZXItc2VjcmV0by1jbGF2ZS1wYXJhLWp3dC1kZS1yZW50YWNhcm5vdy0yMDI2LWVuLWNvbnN0cnVjY2lvbg}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}

spring.mail.host=${SPRING_MAIL_HOST:smtp-relay.brevo.com}
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.username=${SPRING_MAIL_USERNAME:}
spring.mail.password=${SPRING_MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.mail.from=${APP_MAIL_FROM:no-reply@rentacarnow.com}
app.mail.from-name=${APP_MAIL_FROM_NAME:RentACarNow}
app.mail.enabled=${APP_MAIL_ENABLED:true}
app.frontend.url=${APP_FRONTEND_URL:http://localhost:5173}

spring.data.web.pageable.default-page-size=10
spring.data.web.pageable.max-page-size=50

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
