spring.application.name=rentacarnow

spring.datasource.url=jdbc:postgresql://localhost:5430/rentacarnow
spring.datasource.username=rentacarnow
spring.datasource.password=rentacarnow
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
